import Head from "next/head";

export default function Header({ title, description }) {
  return (
    <Head>
      <title>{title || "Next App"}</title>
      <meta
        name="description"
        content={description || "Generated by create next app"}
      />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
