import { Inter } from "@next/font/google";
import Navbar from "./navbar";
import Head from "next/head";
import ScrollTopButton from "./scroll-top-button";

const inter = Inter({ subsets: ["latin"] });

export default function Layout({ children }) {
  const { title, description, categories } = children.props;

  return (
    <>
      <Head>
        <title>{title || "Next App"}</title>
        <meta
          name="description"
          content={description || "Generated by create next app"}
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={inter.className}>
        <Navbar categories={categories} />
        <ScrollTopButton />
        <main>{children}</main>
      </div>
    </>
  );
}
